[package]
name = "base64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
base64_text = "0.1.2"
clap = { version = "4.3.19", features = ["derive"] }
arboard = "3.2.0"
