name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
        tool: [guid, base64]

    steps:
      - uses: actions/checkout@v4

      - name: Compile and release ${{ matrix.tool }} for ${{ matrix.target }}
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          SRC_DIR: ${{ matrix.tool }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: LICENSE ${{ matrix.tool }}/README.md