name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [
          { name: x86_64-pc-windows-gnu, extension: zip },
          { name: x86_64-unknown-linux-musl, extension: tar.gz },
          { name: x86_64-apple-darwin, extension: zip }
        ]
        tool: [ guid , base64]

    steps:
      - uses: actions/checkout@v4

      - name: Compile and release ${{ matrix.tool }} for ${{ matrix.target.name }}
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          SRC_DIR: ${{ matrix.tool }}
          RUSTTARGET: ${{ matrix.target.name }}
          ARCHIVE_NAME: ${{ matrix.tool }}-${{ matrix.target.name }}-${{ github.event.release.tag_name }}.${{ matrix.extension }}
          ARCHIVE_TYPES: ${{ matrix.extension }}
          EXTRA_FILES: LICENSE ${{ matrix.tool }}/README.md